// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package line

// Injectors from wire.go:

func InitializeApi() ApiInterface {
	apiInterface := NewApi()
	return apiInterface
}
